from decision_making.src.global_constants import *

# Dictionary of topic pipelining for DDS mock
TOPIC_PIPELINE_DICTIONARY = {
    NAVIGATION_PLAN_PUBLISH_TOPIC: [BEHAVIORAL_NAV_PLAN_READER_TOPIC],
    STATE_PUBLISH_TOPIC: [TRAJECTORY_STATE_READER_TOPIC, BEHAVIORAL_STATE_READER_TOPIC],
    BEHAVIORAL_TRAJECTORY_PARAMS_PUBLISH_TOPIC: [TRAJECTORY_PARAMS_READER_TOPIC]

}

DDS_PUB_SUB_MOCK_NAME_FOR_LOGGING = "DDS_PUB_SUB_MOCK"

MAP_SERVICE_ABSOLUTE_PATH = 'mapping.src.service.map_service.MapService.get_instance'
